# Generated by Django 4.0.4 on 2023-10-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_ministery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='category',
            new_name='title',
        ),
    ]
