# Generated by Django 4.0.4 on 2023-10-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_category_galleryimage_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Minister',
        ),
    ]
