# Generated by Django 4.0.4 on 2023-10-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_guidelines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteGuidelines',
        ),
    ]
