# Generated by Django 4.0.4 on 2023-10-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_delete_siteguidelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
