# Generated by Django 4.0.4 on 2023-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_guidelines_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
