# Generated by Django 4.0.4 on 2023-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_guidelines_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
    ]
