# Generated by Django 4.0.4 on 2023-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_eventcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcards',
            name='description',
            field=models.CharField(blank=True, max_length=900000, null=True),
        ),
    ]
